# Declare global variables used across the package to avoid check warnings
utils::globalVariables(c(
  ".", "Q1", "days_next_game", "days_rest", "fg_pct", "fga", "fgm",
  "gameID", "game_count", "game_count_season", "game_date", "game_date_est",
  "game_id", "game_label", "game_list", "inBonus", "is_b2b", "is_b2b_first",
  "is_b2b_second", "loc_x", "loc_y", "matchup", "opp_days_next_game",
  "opp_days_rest", "opp_game_count", "opp_game_count_season", "opp_is_b2b",
  "opp_is_b2b_first", "opp_is_b2b_second", "opp_pts", "opp_team_abbreviation",
  "opp_team_id", "opp_team_name", "periodType", "player_id", "plus_minus",
  "process_team_games", "pts", "score", "season_year", "shot_attempted_flag",
  "shot_distance", "shot_made_flag", "shot_type", "shot_zone_basic",
  "teamName", "team_abbreviation", "team_city", "team_id", "team_name",
  "timeoutsRemaining", "wl", "statistics", "event_index", "eventmsgactiontype",
  "eventmsgactiontype.x", "eventmsgactiontype.y", "eventmsgtype",
  "eventmsgtype.x", "eventmsgtype.y", "eventnum", "fg_and_one", "ft_end_id",
  "ft_id", "ft_start_id", "group_id", "heave", "homedescription.x",
  "homedescription.y", "lineup_after", "lineup_after_away", "lineup_after_home",
  "lineup_away", "lineup_before_away", "lineup_before_home", "lineup_home",
  "lineup_initial", "lineup_initial_away", "lineup_initial_home", "name_player",
  "pctimestring", "player1_id", "player1_name", "player1_team_abbreviation",
  "player1_team_id", "player2_name", "player2_team_abbreviation",
  "player3_name", "player_in", "player_out", "possession", "possession.x",
  "possession.y", "scoremargin", "secs_left_quarter", "secs_passed_game",
  "shot_pts_away", "shot_pts_home", "start_poss", "team_location",
  "team_player", "video_available_flag", "visitordescription.x",
  "visitordescription.y", "wctimestring", "missing_starters",
  "home_corrections", "visitor_corrections", "delete_rows", "corrections",
  "data", "min_sec", "person_id", "display_first_last", "birthdate", "school",
  "country", "height", "weight", "season_exp", "jersey", "position",
  "from_year", "to_year", "draft_year", "draft_round", "draft_number",
  "height_inches", "name", "player_first_name", "player_last_name",
  "player_name", "ast", "blk", "color_index", "division_id", "dreb",
  "dreb_opp", "drtg", "fg3_pct", "fg3a", "fg3m", "foul", "ft_pct", "fta", "ftm",
  "homedescription", "lineup", "lineup_changed", "lineup_index", "lineup_pts",
  "minutes_played", "opp_lineup", "oreb", "oreb_opp", "ortg", "person2type",
  "poss", "poss_opp", "prev_lineup", "pts_opp", "reb", "starter", "stl",
  "team_color", "team_color_1", "team_color_2", "team_color_3", "time_played",
  "total_minutes", "total_seconds", "tov", "usage_pct", "visitordescription",
  "away_list", "away_team_name", "block", "home_list", "home_team_name",
  "interval", "lineup_away_pt", "lineup_home_pt", "lineup_role", "lineup_tmp",
  "matchup_index", "mdy_hm", "next_sec", "period", "player",
  "player3_team_abbreviation", "player_role", "player_team", "poss_team",
  "possessions", "prev_opp_lineup", "prev_period", "sec_played", "starters",
  "steal", "total_sec", "x", "x1", "x2", "xmax", "xmin", "y", "y1", "y2",
  "years", "ymax", "ymin"
))
